{% set name = "WTForms" %}
{% set version = "2.3.3" %}
{% set sha256 = "81195de0ac94fbc8368abbaf9197b88c4f3ffd6c2719b5bf5fc9da744f3d829c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python 2.7|>=3.5
    - pip
    - babel >=2.6.0
  run:
    - python 2.7|>=3.5
    - markupsafe

test:
  imports:
    - wtforms
    - wtforms.csrf
    - wtforms.fields
    - wtforms.widgets

about:
  home: http://wtforms.simplecodes.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A flexible forms validation and rendering library for Python
  doc_url: http://wtforms.readthedocs.io
  dev_url: https://github.com/wtforms/wtforms

extra:
  recipe-maintainers:
    - mcs07
    - synapticarbors
