{% set name = "WTForms" %}
{% set version = "3.0.1" %}
{% set sha256 = "6b351bbb12dd58af57ffef05bc78425d08d1914e0fd68ee14143b7ade023c5bc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - babel >=2.6.0
  run:
    - python >=3.6
    - markupsafe

test:
  imports:
    - wtforms
    - wtforms.csrf
    - wtforms.fields
    - wtforms.widgets

about:
  home: http://wtforms.simplecodes.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A flexible forms validation and rendering library for Python
  doc_url: http://wtforms.readthedocs.io
  dev_url: https://github.com/wtforms/wtforms

extra:
  recipe-maintainers:
    - mcs07
    - synapticarbors
